# Generated by Django 5.1.7 on 2025-03-10 07:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support',
            new_name='SupportSection',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='supportsection',
            options={'ordering': ['reason'], 'verbose_name': 'Раздел тех. поддержки', 'verbose_name_plural': 'Разделы тех. поддержки'},
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 10, 7, 57, 32, 58056, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='kit_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кит номер тарелки'),
        ),
    ]
