# Generated by Django 5.1.7 on 2025-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0005_rename_subscription_type_payment_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.CharField(choices=[('standard', 'Стандарт - 15 000 ₽/мес'), ('flat', 'Флэт - 63 000 ₽/мес'), ('global', 'Глобал - 49 000 ₽/мес')], max_length=255, verbose_name='Тип подписки'),
        ),
    ]
