# Generated by Django 5.1.7 on 2025-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0006_alter_payment_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='publications', verbose_name='Фото или видео'),
        ),
    ]
