# Generated by Django 5.1.7 on 2025-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0007_alter_publication_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('standard', 'Стандарт - 15 000 ₽/мес'), ('flat', 'Флэт - 63 000 ₽/мес'), ('global', 'Глобал - 49 000 ₽/мес')], max_length=255, null=True, verbose_name='Тип подписки'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('buying', 'Покупка тарелки'), ('connection', 'Подключение тарелки'), ('subscription', 'Оплата подписки')], default='subscription', max_length=255, verbose_name='Тип оплаты'),
            preserve_default=False,
        ),
    ]
