# Generated by Django 5.1.7 on 2025-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0008_remove_payment_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Уникальный ID заказа'),
        ),
    ]
