# Generated by Django 5.1.7 on 2025-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0009_payment_amount_payment_description_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не оплачено'), (1, 'Предавторизованная сумма захолдирована'), (2, 'Оплачено'), (3, 'Отменено'), (4, 'Оформлен возврат'), (5, 'Инициирована авторизация через ACS банка-эмитента'), (6, 'Отклонено')], verbose_name='Статус'),
        ),
    ]
