# Generated by Django 5.1.7 on 2025-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink', '0011_faq_client_onetime_payment_supportsection_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('buying', 'Покупка тарелки'), ('connection', 'Подключение тарелки'), ('onetime_payment', 'Единоразовый платеж'), ('subscription', 'Оплата подписки')], max_length=255, verbose_name='Тип оплаты'),
        ),
    ]
